/-  Property-based conjecture miner for the FST library.

    Run with:  lake env lean scripts/conjecture_miner.lean

    Method: enumerate all words up to a length bound over a small finite alphabet,
    evaluate a battery of candidate algebraic laws on every tuple via the library's
    *computable* functions (lcp, delay, pdist, wpow, structOK, rtRuns, loopOutputs),
    and classify each law as SURVIVES (no counterexample found in the search space —
    a conjecture worth proving) or refuted (with the first counterexample).

    This is the engine that surfaced `structOK_swap`, `structOK_self`,
    `twinning_structOK_symm`, and `rtRuns_demoEchoδ`, now proved in FST.lean.        -/
import FST
open FST

abbrev W := List (Fin 2)
def pool (n : Nat) : List W := wordsLE 2 n

def check2 (p : W → W → Bool) (xs : List W) : Option (W × W) :=
  (xs.flatMap (fun a => xs.map (fun b => (a, b)))).find? (fun (a, b) => ! p a b)
def check3 (p : W → W → W → Bool) (xs : List W) : Option (W × W × W) :=
  (xs.flatMap (fun a => xs.flatMap (fun b => xs.map (fun c => (a,b,c))))).find?
    (fun (a,b,c) => ! p a b c)
def check4 (p : W → W → W → W → Bool) (xs : List W) : Option (W × W × W × W) :=
  (xs.flatMap (fun a => xs.flatMap (fun b => xs.flatMap (fun c => xs.map (fun d => (a,b,c,d)))))).find?
    (fun (a,b,c,d) => ! p a b c d)

def r2 (n : String) (p : W → W → Bool) (xs : List W) : String :=
  match check2 p xs with | none => "  SURVIVES: "++n | some (a,b) => "  refuted : "++n++s!"  ({a},{b})"
def r3 (n : String) (p : W → W → W → Bool) (xs : List W) : String :=
  match check3 p xs with | none => "  SURVIVES: "++n | some (a,b,c) => "  refuted : "++n++s!"  ({a},{b},{c})"
def r4 (n : String) (p : W → W → W → W → Bool) (xs : List W) : String :=
  match check4 p xs with | none => "  SURVIVES: "++n | some (a,b,c,d) => "  refuted : "++n++s!"  ({a},{b},{c},{d})"

def P := pool 3

-- The four laws that survived and were subsequently PROVED in FST.lean:
#eval IO.println "=== Laws the miner surfaced (all now theorems in FST.lean) ==="
#eval IO.println (r4 "structOK swap-invariance  (→ structOK_swap)"
  (fun a1 a2 b1 b2 => structOK a1 a2 b1 b2 == structOK a2 a1 b2 b1) P)
#eval IO.println (r2 "structOK diagonal  (→ structOK_self)"
  (fun a b => structOK a a b b) P)
#eval IO.println (r2 "echo run = identity  (→ rtRuns_demoEchoδ)"
  (fun x _ => rtRuns demoEchoδ 0 x == [(x, 0)]) P)

-- A sampling of the metric/word laws the miner re-validated (already theorems):
#eval IO.println "=== Sample re-validated library laws ==="
#eval IO.println (r2 "pdist symmetric" (fun x y => pdist x y == pdist y x) P)
#eval IO.println (r3 "pdist triangle" (fun x y z => pdist x z ≤ pdist x y + pdist y z) P)
#eval IO.println (r2 "delay self-append" (fun z w => delay z (z ++ w) == ([], w)) P)

-- ===========================================================================
-- ROTATION BATTERY: laws the miner surfaced about cyclic rotation, and the
-- naive conjectures it REFUTED (documenting the saturation behaviour that the
-- proofs in FST.lean had to account for).
-- ===========================================================================
def Pr : List W := wordsLE 2 4

#eval IO.println "=== ROTATION: survivors (now theorems rot_* in FST.lean) ==="
#eval IO.println (
  match Pr.find? (fun w => rot w.length w != w) with
  | none => "  SURVIVES: rot |w| w = w                 (→ rot_length_self)"
  | some w => s!"  refuted: {w}")
#eval IO.println (
  match Pr.find? (fun w => rot 0 w != w) with
  | none => "  SURVIVES: rot 0 w = w                   (→ rot_zero)"
  | some w => s!"  refuted: {w}")
#eval IO.println (
  match (Pr.flatMap (fun w => (List.range 5).flatMap (fun a => (List.range 5).map (fun b => (w,a,b))))).find?
      (fun (w,a,b) => rot a (rot b w) != rot b (rot a w)) with
  | none => "  SURVIVES: rot a (rot b w) = rot b (rot a w)   (→ rot_comm)"
  | some (w,a,b) => s!"  refuted: w={w} a={a} b={b}")

#eval IO.println "=== ROTATION: naive conjectures the miner REFUTED (negative results) ==="
-- 'rotation wraps modulo length' -- FALSE because rot saturates for k ≥ |w|.
#eval IO.println (
  match (Pr.filter (fun w => w.length > 0)).flatMap (fun w => (List.range 8).map (fun k => (w,k))) |>.find?
      (fun (w,k) => rot k w != rot (k % w.length) w) with
  | none => "  (unexpectedly survived) rot k w = rot (k%|w|) w"
  | some (w,k) => s!"  REFUTED as expected: rot k w = rot (k%|w|) w   counterexample w={w}, k={k}")
-- 'rot is generated by rot 1' -- FALSE for the same saturation reason.
#eval IO.println (
  match (Pr.flatMap (fun w => (List.range 6).map (fun k => (w,k)))).find?
      (fun (w,k) => rot (k+1) w != rot 1 (rot k w)) with
  | none => "  (unexpectedly survived) rot (k+1) w = rot 1 (rot k w)"
  | some (w,k) => s!"  REFUTED as expected: rot (k+1) w = rot 1 (rot k w)   counterexample w={w}, k={k}")
